### ISSUE TITLE
dependency no longer available

### ISSUE THREAD

**Issue by gpapadog** [czigler/arepa#10]
Zipcode R package on which arepa depends is no longer available

**Comment by mbsabath** [comment]
Solution to this is the install zipcode using `devtools::install_github("cran/zipcode")` prior to installing arepa. The `DESCRIPTION` file has been updated to hopefully make this automatic, but using this definitely works.

Long term, we may want to look in to finding different sources of zip code centroids that can be directly hosted in the package.
