### ISSUE TITLE
load_annual_average fails for one year

### ISSUE THREAD

**Issue by gpapadog** [czigler/arepa#2]
years <- 2013
annual <- load_annual_average(years)  # Fails

years <- c(2012, 2013)
annual <- load_annual_average(years)
annual <- subset(annual, Year == 2013)  # Works

**Comment by cchoirat** [comment]
I'm on a tablet.  How about:

annual <- load_annual_average(as.character(years))

?

**Comment by gpapadog** [comment]
Yep, that works!

g

On May 29, 2017, at 12:32 PM, Christine Choirat <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm on a tablet. How about:

annual <- load_annual_average(as.character(years))

?

**Comment by cchoirat** [comment]
Should be easy to fix.  Thanks for pointing out!

**Comment by mbsabath** [comment]
fixed this as well, the issue was that when `seq` is passed a single argument (and when that argument is a year) it would iterate over the number in the year instead of the single year. I changed this to use length to guide the iteration.
