### ISSUE TITLE
Error in loading annual average files

### ISSUE THREAD

**Issue by mbsabath** [czigler/arepa#6]
Downloading errors have been fixed in mbsbath/arepa bug_fix branch, but this error remains. I'm not really sure where to begin with it.

 Error in `:=`(Monitor, paste(sprintf("%02d", as.numeric(State.Code)),  : 
  Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").

**Comment by mbsabath** [comment]
This is a different one, I think the error arrises when trying to reshape the csv

**Comment by mbsabath** [comment]
The error is in this line:

https://github.com/czigler/arepa/blob/826075d9a902eb1f226ac0da879cbef05f4ff641/R/arepa.R#L80

I'm not totally sure what this line is doing, so starting on debugging it, especially with the type errors is difficult.

**Comment by mbsabath** [comment]
The error exists in the `load_daily_data()` function as well

**Comment by cchoirat** [comment]
From memory:

Recreate a FIPS from State.Code and County.Code, by forcing heading zeroes
to be kept.  For example

State.Code <- 2
County.Code<- 40
Site.Num <- 7

Would give ""02 040 - 0007".

The := assignment might give issues with the new data.table.

**Comment by mbsabath** [comment]
I can go in and fix that. Site.Num is always 4 digits, county code is always 3?

**Comment by cchoirat** [comment]
Can you please open a separate ticket for load_daily_data?  Thanks!

**Comment by mbsabath** [comment]
Error resolved awhile back, closing
